# todo use rabbitmq - deploy rabbit in kubernetes and expose monitoring ingress for auto
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue-production-mex-autoscale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue-production-mex-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-production-mex-deployment
  namespace: default
spec:
  template:
    metadata:
      name: catalogue-production-mex-deployment-template
      labels:
        application: catalogue
        environment: production
        application-type: data-services
        owner: yogesh
        version: v0.1
        type: deployment
    spec:
      restartPolicy: Always
      containers:
        - name: catalogue-production-mex-container
          image: gcr.io/byprice-backend/production/catalogue:master
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 512m
            requests:
              cpu: 256m
              memory: 1024Mi
          command: ['/bin/bash' , '-c', 'echo Starting container !! && source bin/run.sh']
          env:
            - name: "STREAMER_PASS"
              valueFrom:
                secretKeyRef:
                  name: data-service-secret-production-mex
                  key: STREAMER_PASS
            - name: "SQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: data-service-secret-production-mex
                  key: SQL_PASSWORD
  selector:
    matchLabels:
      application: catalogue
      environment: production
      application-type: data-services
      owner: yogesh
      version: v0.1
      type: deployment
