apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-item-data-service-production-mex-deployment
  namespace: default
spec:
  template:
    metadata:
      name: catalogue-item-data-service-production-mex-deployment-template
      labels:
        application: catalogue-item-data-service
        environment: production
        application-type: data-services
        owner: oscar
        version: v0.1
        type: deployment
    spec:
      restartPolicy: Always
      containers:
        - name: catalogue-item-data-service-production-mex-container
          image: gcr.io/byprice-backend/production/data-service/catalogue_item:master
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 512m
            requests:
              cpu: 256m
              memory: 1024Mi
          command: ['/bin/bash' , '-c', 'echo Starting container !! && source bin/run_item_data_service.sh']
          env:
            - name: "STREAMER_PASS"
              valueFrom:
                secretKeyRef:
                  name: data-service-secret-production-mex
                  key: STREAMER_PASS
            - name: "SQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: data-service-secret-production-mex
                  key: SQL_PASSWORD
  selector:
    matchLabels:
      application: catalogue-item-data-service
      environment: production
      application-type: data-services
      owner: oscar
      version: v0.1
      type: deployment
