Parameters:
  Cluster:
    Type: String
  DesiredCount:
    Type: String
  Image:
    Type: String
  Role:
    Type: String
  TargetGroupArn:
    Type: String
  SecretsBucketName:
    Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      Role: !Ref Role
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: catalogue
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroupArn

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: catalogue
      ContainerDefinitions:
        - Name: catalogue
          Image: !Ref Image
          Memory: 512
          PortMappings:
            - HostPort: 0
              ContainerPort: 80
            - HostPort: 0
              ContainerPort: 8000
          EntryPoint:
            - /bin/bash
            - /catalogue/bin/run.sh
          Environment:
            - Name: SECRETS_BUCKET_NAME
              Value: !Ref SecretsBucketName
          WorkingDirectory: /catalogue
