apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-web-service-development-mex-deployment
  namespace: default
spec:
  template:
    metadata:
      name: catalogue-web-service-development-mex-deployment-template
      labels:
        application: catalogue-web-service
        environment: development
        application-type: web-service
        owner: yogesh
        version: v0.1
        type: deployment
    spec:
      restartPolicy: Always
      containers:
        - name: catalogue-web-service-development-mex-container
          image: gcr.io/byprice-backend/development/web-service/catalogue:master
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 512m
            requests:
              cpu: 256m
              memory: 1024Mi
          command: ['/bin/bash' , '-c', 'echo Starting container !! && source bin/run_web_service.sh']
          env:
            - name: "SQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: web-service-secret-development-mex
                  key: SQL_PASSWORD
  selector:
    matchLabels:
      application: catalogue-web-service
      environment: development
      application-type: web-service
      owner: yogesh
      version: v0.1
      type: deployment
