# todo use rabbitmq - deploy rabbit in kubernetes and expose monitoring ingress for auto
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue-web-service-development-mex-autoscale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue-web-service-development-mex-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50